###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:

- name: build 
  image: node:14.18.1
  commands:
    - yarn install --pure-lockfile
    - yarn run build

- name: publish to Dockerhub image
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/lab3
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
    - master
    - main

- name: publish readme to Dockerhub
  image: thomaslacaze/dockerhub-description:2.4.1
  pull: always
  settings:
    repository: thomaslacaze/lab3
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    readme: /drone/src/README.md
  when:
    branch:
    - master
    - main

---
kind: pipeline
type: docker
name: deploy

steps:
- name: build
  image: node
  volumes:
  - name: cache
    path: /drone/src/dist/itm-frontend
  commands:
  - yarn install --pure-lockfile
  - yarn run build

- name: Upload to S3
  image: plugins/s3
  volumes:
  - name: cache
    path: /drone/src/${CI_BUILD_TARGET}
  settings:
    bucket: 
      from_secret: aws_bucket_name
    access_key: 
      from_secret: aws_access_key
    secret_key: 
      from_secret: aws_secret_key
    source: ${CI_BUILD_TARGET}/*
    region: eu-west-1
    target: /public

trigger:
  event:
  - promote

volumes:
- name: cache
  temp: {}