version: '2.1'
services:
    lab3:
      image: thomaslacaze/lab3
      container_name: lab3
      volumes:
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      environment: 
        - REACT_APP_BACKEND_URL=http://localhost:8080
      ports:
        - 3000:3000
